# Generated by Django 3.2.9 on 2022-01-10 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='digital',
            new_name='deliverable',
        ),
    ]
