# Generated by Django 3.2.9 on 2022-01-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_rename_adress_shippingadress_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAdress',
            new_name='ShippingAddress',
        ),
    ]
